version: '3.9'
services:
  metabase-keycloak:
    image: metabase/metabase-enterprise:v1.48.3
    container_name: metabase-keycloak
    hostname: metabase-keycloak
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      - "MB_SITE_URL=http://localhost:3000"
      - "MB_SAML_IDENTITY_PROVIDER_ISSUER=http://localhost:9090/auth/realms/master"
      - "MB_SAML_IDENTITY_PROVIDER_URI=http://localhost:9090/auth/realms/master/protocol/saml"
      - "MB_ENABLE_PASSWORD_LOGIN=false"
      - "MB_SAML_ENABLED=false"
      - "MB_SAML_ATTRIBUTE_EMAIL=email"
      - "MB_SAML_ATTRIBUTE_FIRSTNAME=givenName"
      - "MB_SAML_ATTRIBUTE_LASTNAME=sn"
      - "MB_SAML_APPLICATION_NAME=metabase"
      - "MB_PREMIUM_EMBEDDING_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      - "MB_EMAIL_SMTP_HOST=maildev-keycloak"
      - "MB_EMAIL_SMTP_PASSWORD=password"
      - "MB_EMAIL_SMTP_PORT=25"
      - "MB_EMAIL_SMTP_SECURITY=none"
      - "MB_EMAIL_SMTP_USERNAME=admin"
    networks:
      - metanet1-keycloak
    healthcheck:
      test: ["CMD-SHELL", "curl -f -X GET -I http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 3072M
        reservations:
          cpus: '4'
          memory: 1536M
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    ports:
      - 9090:8080
    networks:
      - metanet1-keycloak
    environment:
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=password"
      - "KC_DB=postgres"
      - "KC_DB_URL_HOST=postgres-keycloak"
      - "KC_DB_URL_PORT=5432"
      - "KC_DB_URL_DATABASE=keycloak"
      - "KC_DB_USERNAME=keycloak"
      - "KC_DB_PASSWORD=keycloak"
    command: start-dev --hostname=localhost
  maildev-sub-keycloak:
    image: maildev/maildev:2.1.0
    container_name: maildev-sub-keycloak
    hostname: maildev-sub
    ports:
    - "3001:1080"
    - "3025:1025"
    networks:
    - metanet1-keycloak
    cpus: 1
    mem_limit: 128m
networks:
  metanet1-keycloak:
    driver: bridge
